### ISSUE TITLE
适配评论区笔记

### ISSUE THREAD

**Issue by PolarLinda6** [jk278/bilibili-mobile#1]
![Screenshot_2024-09-21-00-08-43-597_mark.via-edit.jpg](https://github.com/user-attachments/assets/ec2ff14c-3638-4f18-8b64-ad7dc8d4c96d)

【深度剖析：金丝眼镜，为何让男性魅力瞬间飙升？｜男性性张力、无框眼镜、全框眼镜、半框眼镜】 https://www.bilibili.com/video/BV1594nerEac/?share_source=copy_web&vd_source=4403ca5ab4b7a68d281050c31d7c971f

**Comment by jk278** [comment]
已更 5.0.4.1

**Comment by PolarLinda6** [comment]
建议增加个点击笔记外区域，自动关闭

![Screenshot_2024-09-21-09-36-40-025_mark.via-edit.jpg](https://github.com/user-attachments/assets/6a96bcab-c774-4818-8eb8-9dc8dd12d089)

**Comment by jk278** [comment]
5.0.4.2
