### ISSUE TITLE
首页某视频无菜单

### ISSUE THREAD

**Issue by PolarLinda6** [jk278/bilibili-mobile#2]
好像只会遇到该视频出现
![IMG_20240924_155832.jpg](https://github.com/user-attachments/assets/db99c701-8873-4aa4-aa88-49f54d966ef4)

**Comment by jk278** [comment]
没刷到过，我不知道呀。

**Comment by PolarLinda6** [comment]
emmm这好像挺普遍的
![IMG_20240924_202414.jpg](https://github.com/user-attachments/assets/00c3a6c7-f328-4845-9d4c-394504b37a1c)

**Comment by jk278** [comment]
又刷了一两百个视频，没遇到。会不会是啥灰度测试的新推广类别？

**Comment by PolarLinda6** [comment]
emmm试试多看几个这类的视频，再刷

【9月23日更新【永久白嫖】免费领取网易云vip黑胶会员 370天体验券，飙升榜音乐合集 网易云音乐会员vip 网易云热评超音乐爱好者快来呀！】 https://www.bilibili.com/video/BV1cfsXezEmA/?share_source=copy_web&vd_source=4403ca5ab4b7a68d281050c31d7c971f

**Comment by jk278** [comment]
“视频去哪了呢？” “啊叻？视频不见了？”
看不了，多半是灰度测试了。

**Comment by PolarLinda6** [comment]
emmm 给搜索页的视频加个菜单，试一试怎么样呢

**Comment by PolarLinda6** [comment]
emmm 感觉中毒了，经常能遇到。。。 

https://www.bilibili.com/video/BV11LsRemEbj/?source_id=5637&resource_id=__RESOURCEID__&creative_id=164633450&linked_creative_id=164633450&track_id=pbaes.0E95ulrXmpXnqJU8DXAcJhqW2JAHh_eSZCxkBfyRrCuYaA82Jn4EmQ2EZK1IIlsnjJC0932l89zTa3XTTfsKStBUBIQ0-7INr5cSyIhA6WfpMMCM82wGmMwrw13VXnwwq7rSNNrLwCN-YXPruASwo92WajakGny6Vbb3oMOHLU3dLbQkdhIYYsRSjpgKRDWc&from_spmid=__FROMSPMID__&trackid=web_pegasus_7.router-web-pegasus-1672164-774956c8f8-747ng.1727183773784.536&request_id=1727183773795q172a25a172a193q3640&caid=__CAID__&vd_source=1ca05631b9ea1f71f563837aab98b21c

![Screenshot_2024-09-24-21-16-30-936_mark.via.png](https://github.com/user-attachments/assets/deab1f3f-0f9e-4679-8488-96b9421eba53)

**Comment by jk278** [comment]
> emmm 给搜索页的视频加个菜单，试一试怎么样呢

搜索页的视频没有默认的更多操作，不打算加。

**Comment by jk278** [comment]
我把链接里的视频看完了，首页还是刷不到。

**Comment by PolarLinda6** [comment]
https://github.com/user-attachments/assets/e1b5ff6f-663f-4231-b577-d6c9919d6fa9

**Comment by jk278** [comment]
这是 up 头像的鼠标悬浮弹窗，根据 up 头像定位的，部分触摸操作会触发，但是没适配这个（直接点进 up 主页就行）。好像点一下其它地方就隐藏了。

**Comment by PolarLinda6** [comment]
> 这是 up 头像的鼠标悬浮弹窗，根据 up 头像定位的，部分触摸操作会触发，但是没适配这个（直接点进 up 主页就行）。好像点一下其它地方就隐藏了。

emmm 那建议屏蔽掉吧
