### ISSUE TITLE
wx

### ISSUE THREAD

**Issue by PolarLinda6** [jk278/bilibili-mobile#4]
给个微信，github issue 不方便

**Comment by jk278** [comment]
你手机上有邮箱 APP 没？给我发邮箱我也是秒收到的。

**Comment by PolarLinda6** [comment]
> 你手机上有邮箱 APP 没？给我发邮箱我也是秒收到的。

ok，你邮箱多少

**Comment by jk278** [comment]
> ok，你邮箱多少

邮箱之前解散的群里有啊，你没看到嘛？

**Comment by PolarLinda6** [comment]
> > ok，你邮箱多少
> 
> 邮箱之前解散的群里有啊，你没看到嘛？

没复制。。。。

**Comment by jk278** [comment]
那你邮箱给我，我给你发条信息

**Comment by PolarLinda6** [comment]
3585409386@qq.com

ps: 记得删除这个issue
