### ISSUE TITLE
私信适配

### ISSUE THREAD

**Issue by PolarLinda6** [jk278/bilibili-mobile#5]
![IMG_20240926_233116.jpg](https://github.com/user-attachments/assets/2bbe60c2-647f-4f0b-a2e3-be39d0bd6af6)

把红框区域干掉，总是去不掉

支持选中复制（是b站截取了长按菜单吗? 如果能使用via的自带长按选项更好了）

**Comment by jk278** [comment]
OK

**Comment by jk278** [comment]
5.1

**Comment by PolarLinda6** [comment]
![Screenshot_2024-09-27-09-59-00-918_mark.via.jpg](https://github.com/user-attachments/assets/7b2084e5-c5d3-4af0-bf9f-85fae306af1b)

还是复制不了，emmm

**Comment by jk278** [comment]
5.1.3
