### ISSUE TITLE
视频页优化

### ISSUE THREAD

**Issue by PolarLinda6** [jk278/bilibili-mobile#6]
![Screenshot_2024-09-27-00-05-43-981_mark.via-edit.jpg](https://github.com/user-attachments/assets/2119f1fd-42da-4975-b21e-40bd522b3a1f)

将标签栏与简介归纳至标题展开按钮中

![IMG_20240927_000825.jpg](https://github.com/user-attachments/assets/10c966a1-f1af-4e9b-9b4f-9bf6f3e8ca6b)

时间未对齐，并且在开启隐藏标题附加声明的选项后，仍显示附加声明

【LOL今日新资讯:全场半价30号开启!无限乱斗即将回归!魔域梦魇有49元礼盒!】 https://www.bilibili.com/video/BV1qcxge5Eze/?share_source=copy_web&vd_source=4403ca5ab4b7a68d281050c31d7c971f

**Comment by jk278** [comment]
隐藏附加声明不对展开弹窗生效

**Comment by jk278** [comment]
5.1
