### ISSUE TITLE
视频页

### ISSUE THREAD

**Issue by PolarLinda6** [jk278/bilibili-mobile#8]
![IMG_20240927_191321.jpg](https://github.com/user-attachments/assets/5063e196-828c-4b53-bce7-85be75f33b2f)

标题: 可完整显示标题时，不显示展开按钮
简介: 没有简介时，不显示展开按钮

![Screenshot_2024-09-27-19-20-59-003_mark.via-edit.jpg](https://github.com/user-attachments/assets/c3a10816-82a9-47bd-ab47-53d580552a6a)

标题展开错误

**Comment by PolarLinda6** [comment]
使用折叠时自动展开 

![IMG_20240927_192329.jpg](https://github.com/user-attachments/assets/c48d478f-f8e5-44a9-8244-34f4952b7c58)

**Comment by PolarLinda6** [comment]
将简介按钮放置在如图区域（原区域看着太难受）
![Screenshot_2024-09-27-19-26-53-840_mark.via-edit.jpg](https://github.com/user-attachments/assets/bcd08133-2fe5-4ccf-b614-f2588c3292ce)

**Comment by jk278** [comment]
标题展开错误的，发一个链接

**Comment by PolarLinda6** [comment]
> 标题展开错误的，发一个链接

【一口气24小时看完《绝命毒师》+《续命之徒》（含彩蛋、色彩、音乐解读）【墨菲】】 https://www.bilibili.com/video/BV1QN4y1B7Xu/?p=2&share_source=copy_web&vd_source=4403ca5ab4b7a68d281050c31d7c971f

**Comment by jk278** [comment]
5.1.5
